### ISSUE TITLE
CA-sup datasets

### ISSUE THREAD

**Issue by lyh200095** [JianghaiSCU/RealSH#2]
Can you upload the CA-sup datasets？

**Comment by JianghaiSCU** [comment]
The dataset is too large so we can't upload it, but we have given the code to generate the data, please refer to https://github.com/JianghaiSCU/RealSH/blob/dcd872bdab5c5b191a4ae5ddfec89b0fe9086a73/dataset/pre_processing.py#L42

**Comment by lyh200095** [comment]
Thank you for your answer!
