### ISSUE TITLE
Make Datasets

### ISSUE THREAD

**Issue by DoongLi** [JianghaiSCU/RealSH#4]
Hi，we want to make some image pairs Dataset like your paper used，and test this methods in our datasets，How do we make it？

**Comment by JianghaiSCU** [comment]
The code used to generate the labeled data can be found in https://github.com/JianghaiSCU/RealSH/blob/dcd872bdab5c5b191a4ae5ddfec89b0fe9086a73/dataset/pre_processing.py#L42

**Comment by DoongLi** [comment]
Thx for your reply, Is there any open source for the feature point used by this dataset?

**Comment by JianghaiSCU** [comment]
We do not rely on feature points for training, while the evaluation files are based on the matched feature points.

**Comment by JianghaiSCU** [comment]
You can use https://github.com/zhengchen1999/HI-Diff/issues/8 to prepare your own evaluation files.

**Comment by JianghaiSCU** [comment]
You can use https://people.csail.mit.edu/celiu/OpticalFlow to prepare your own evaluation files.
